name: publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Updated registry version'
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Validate version format
        run: |
          if [[ ! ${{ github.event.inputs.version }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Version '${{ github.event.inputs.version }}' is not a valid semver version."
            exit 1
          fi

      - name: Checkout repository source
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Configure git
        run: |
          git config --global user.name "Kruithne"
          git config --global user.email "kruithne@gmail.com"

      - name: Install dependencies
        run: npm ci
        
      - name: Install TypeScript
        run: npm install -g typescript

      - name: Compile TypeScript
        run: tsc

      - name: ESLint check
        run: npx eslint .

      - name: Update package version
        run: npm version ${{ github.event.inputs.version }} -m "Release ${{ github.event.inputs.version }} ✨"

      - name: Push changes
        run: git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            README.md
            LICENSE
            package.json
            index.js
            index.d.ts
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          body: |
            Release ${{ github.event.inputs.version }} ✨

      - name: Publish to npm.js
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}